### PR TITLE
Search Engine Friendly Data output

### LINKED ISSUE #12: Search engine friendly dataset output
This may be a bit of a lift to make happen, but it would turn the [/api/gtc](https://greenville-cal-service.herokuapp.com/api/gtc) output into something that could be fed to a search engine or graph-based too (see [LevelGraph](http://levelgraph.io) and it's [Playground](https://wileylabs.github.io/levelgraph-playground/)) with meaningful results (rich snippet display, filtering down to events happening at a single place, etc).

Here's an example of the current output (which search engines can't make much out of since it uses a "colloquial" vocabulary--only known to the developers here):
```json
[
  {
    "created_at": "2018-08-09T22:51:43Z", 
    "data_as_of": "2019-01-27T05:43:14Z", 
    "description": "Come and Design, Write Copy, Hack on the Code for Greenville Projects. We won't do much updating during this meeting, it's really around getting down to work. If you are attending for the first time, you may want to start with our monthly Brigade Meeting on 3rd Thursdays. If you want to join in and share your skills this is the meetup for you! Working on:<br/>* Android Tolley Tracker Client App<br/>* iOS Trolley Tracker Agent App*<br/>* Trolley Tracker API<br/>* Open Data API<br/>* Trolley Tracker Design and Marketing *After 6pm the Bank of America elevators are not available to the public so it is best to enter from the 3rd floor of the Richardson Street public parking garage*", 
    "event_name": "Code For Greenville Work Night", 
    "group_name": "Code for Greenville", 
    "nid": "7", 
    "rsvp_count": 0, 
    "tags": "1", 
    "time": "2019-03-05T23:00:00Z", 
    "url": "https://www.meetup.com/Code-for-Greenville/events/mcrjcqyzfbhb/", 
    "uuid": "47500439-5c63-45ba-9600-be41109bc291", 
    "venue": {
      "address": "101 N. Main St 3rd Floor", 
      "city": "Greenville", 
      "country": "us", 
      "lat": 34.851925, 
      "lon": -82.399948, 
      "name": "OpenWorks", 
      "state": "SC", 
      "zip": null
    }
  }
]
```

Here's a revision that's search engine ready and can be used to create a graph for finding cool stuff (yes it's more verbose...because it does more things with the same data 😄):
```json
{
"@context": [
  "http://schema.org/",
  {"nid": null, "rsvp_count": null, "tags": null, "uuid": null}
],
"@type": "DataFeed",
"dataFeedElement": [
  {
    "@type": "DataFeedItem",
    "dateCreated": "2018-08-09T22:51:43Z", 
    "dateModified": "2019-01-27T05:43:14Z",
    "item": {
      "@type": "Event",
      "description": "Come and Design, Write Copy, Hack on the Code for Greenville Projects. We won't do much updating during this meeting, it's really around getting down to work. If you are attending for the first time, you may want to start with our monthly Brigade Meeting on 3rd Thursdays. If you want to join in and share your skills this is the meetup for you! Working on:<br/>* Android Tolley Tracker Client App<br/>* iOS Trolley Tracker Agent App*<br/>* Trolley Tracker API<br/>* Open Data API<br/>* Trolley Tracker Design and Marketing *After 6pm the Bank of America elevators are not available to the public so it is best to enter from the 3rd floor of the Richardson Street public parking garage*", 
      "name": "Code For Greenville Work Night", 
      "organizer": {
        "@type": "Organization",
        "name": "Code for Greenville"
      }, 
      "nid": "7",
      "rsvp_count": 0, 
      "tags": "1", 
      "startDate": "2019-03-05T23:00:00Z", 
      "url": "https://www.meetup.com/Code-for-Greenville/events/mcrjcqyzfbhb/", 
      "identifier": "urn:uuid:47500439-5c63-45ba-9600-be41109bc291", 
      "location": {
        "@type": "Place",
        "name": "OpenWorks",
        "address": {
          "streetAddress": "101 N. Main St 3rd Floor", 
          "addressLocality": "Greenville",
          "addressRegion": "SC",
          "addressCountry": "USA",
          "postalCode": null
        },
        "geo": {
          "@type": "GeoCoordinates",
          "latitude": 34.851925, 
          "longitude": -82.399948
        }
      }
    }
  }
]}
```

In both examples the array would have more objects in it based on the available data of course.

Also, this object in the `@context` object keeps these terms out of the graph data (as search engines and graphs won't know what to do with them anyhow), so you could also just not output those:
```json
  {"nid": null, "rsvp_count": null, "tags": null, "uuid": null}
```

Hope that mapping solves the hard part anyhow! 😃 

Cheers,
🎩

### LINKED ISSUE #42: Broken Link in deploy_notes_initial.md
In deploy_notes_initial.md, there is a link to creating an Eventbrite token. 

The link is taking me to Eventbrite's website, but the website returns a 404 for this page. 

I believe the current link in the deploy notes can be replaced by this link:
https://www.eventbrite.com/platform/api#/introduction/authentication/1.-get-a-private-token ,
which takes you to Eventbrite's documentation on authentication.

### PR DESCRIPTION
**Pull request by ramonaspence**
This PR contains two major changes. 

First, as in #12 , the API will now respond to requests with the accept header `Content-Type: application/json+ld` with JSON-LD, using the format provided in the aforementioned issue. The API still returns JSON, using our pre-existing format when the request's accept header is `Content-Type: application/json`, as well as by default or when no content_type is specified. This has been tested using Postman. 

The second major change has to do with organization and readability. I have separated the functions used in `update_cal_data.py` to a new file named `update_functions.py` and the functions used in `app.py` are now contained in a new file named `app_functions.py`. 

Some minor changes include an updated link to Eventbrite's description of how to get an Eventbrite token in `deploy_initial.md`. I've also refactored the endpoint using Flask-RESTful's [Resourceful Routing](https://flask-restful.readthedocs.io/en/latest/quickstart.html#resourceful-routing).

Closes #12 
Close #42

### CODE REVIEW

**Comment by allella** [comment]
Alright, so I haven't tried to review this yet, but noticed there's a merge conflict showing on the PR.
https://github.com/codeforgreenville/upstate_tech_cal_service/pull/44/conflicts

Is that something we need to address before this PR is merged?

Also, not a big deal, but it looks like this PR is against the master branch in your fork. It works the same, but typically I see folks creating a branch in their fork and then having a PR against that branch.  This is the least organized and documented project, but perhaps after this major PR we can also copy the CONTRIBUTING.md from the HG repo and tweak it so we have some guidance on branching and PRs.

**Comment by ramonaspence** [comment]
The conflicts that are present are due to the functions being re-organized and the accompanying change in imports, as well as most of `app.py` being refactored. With these changes, the app will behave the same as before with the added support for the JSON-LD format/content type. 

Copying HG's contributing.md sounds like a great idea! Let me know if you'd prefer me to create a new PR from my fork's develop branch. I will go ahead and edit this to include the "closes #12" line.

**Comment by allella** [comment]
@ramonaspence could you try rebasing or merging the master branch into your PR so the conflict gets resolved before merging the PR?

**Review by ramonaspence — COMMENTED** [review]
@allella 
I've rebased and resolved conflicts with individual commits that had been pushed to the codeforgreenville:master branch and I have pushed my master branch to my repo after conflicts were resolved.

It looks like Github is still saying there are conflicts in app.py and I believe those conflicts were resolved during the rebase. With the added files, `update_functions.py` and `app_functions.py`, accepting those incoming changes shouldn't have any adverse effects on functionality. What will be removed from `app.py` as those changes are accepted, have already been moved to those two new files. 

Does that make sense? I'm admittedly still refreshing myself on `git rebase`.

**Comment by allella** [comment]
Okay, so I thought I'd "do it live" and test this branch on the live server since I don't otherwise have a full on environment running Apache and gunicorn.

In any event, this is always a bad idea and things did break temporarily. Of course, I rolled back and I think there was a bug in earlier commits from 2020 and I may have never restarted gunicorn since 2020, so I think those bugs came back in and I had to revert to an even earlier 2020 commit to get it to work.

Still, I'm a persistent idiot who likes to start risky deployments at 1AM.

I got things working on my local machine and then proceeded to do the same on the live server, and of course things broke again.

I have it "working" now on the live server with a checkout of your code from this PR.

The main issues I ran into were installing the new packages.

It's been years since I messed with Conda and I think when I ran conda update it both updated the existing packages and the new packages you'd added to environment.yml.

However, it continued to break because the "six" package was not installed.  "six" seemed to be a dependency of flash_cors and I guess it wasn't auto installed, or else I goofed something up with updating the virtual environment.  Or, this server is on an older version of Python, so maybe that's contributing to that missing "six".

Again, this is working on the live site with your new code. The only immediate bug I see is the URL http://localhost:8000/api/gtc?tags=1 is supposed to only return events with a tag value of 1, but it's returning all of them.  Could you look into that issue and push a commit to get the tags URL working again?

**Comment by allella** [comment]
I should add, we should document the process for what command to run to keep an existing environment up to date.  I ended up running `conda update`, but I'm not even sure that's ideal because it seemed to pull in new versions of all the packages and not just the new ones.  Do you know which command we'd ideally run when environments.yml was changed?

@ramonaspence

**Comment by allella** [comment]
Also, I'm not sure the date parameters are being interpreted because it also seems to return all results

https://events.openupstate.org/api/gtc?start_date=2022-02-03&end_date=2022-02-09

**Comment by allella** [comment]
One last IMPORTANT comment, I reverted the live site back to a 2020 commit to get the API tag and event range working again.  This isn't ideal because it's possibly missing some later 2020 commits, but overall I think it's decent.

If you have time to look into the tags and date range issues in this PR's code, then hopefully that will get us back to a stable point, but with the newer code.

Then, we can address any other bugs and get the documentation in better shape so we're not relying on my memory on what to do when new code deploys with major changes.

**Comment by ramonaspence** [comment]
> I should add, we should document the process for what command to run to keep an existing environment up to date. I ended up running `conda update`, but I'm not even sure that's ideal because it seemed to pull in new versions of all the packages and not just the new ones. Do you know which command we'd ideally run when environments.yml was changed?
> 
> @ramonaspence

@allella 
So the command that I found to use on stackoverflow is:
`conda env update --file environment.yml --prune`
[Here's a link to the documentation for that command](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#updating-an-environment)

>However, it continued to break because the "six" package was not installed. "six" seemed to be a dependency of flash_cors and I guess it wasn't auto installed, or else I goofed something up with updating the virtual environment. Or, this server is on an older version of Python, so maybe that's contributing to that missing "six".

I'm not sure about the "six". But I am running python 3.6, and python is pinned to 3.6 in the `environment.yml`

I think one thing that *may* make setting up the environment a little easier is adding a `requirements.txt` but that's something we can discuss after we get this PR working.

For the tags and date filtering..
I guess I got too excited about getting the JSON-LD to work that I forgot to add back those functions into the code. But those last two commits should have fixed it right up!

So let me know how testing it goes after you try the `conda env update` command.

**Comment by allella** [comment]
Alright, so if I fetch the latest commits on this PR and then run

`conda env update --file environment.yml --prune` then do we think that will resolve the know issues I mentioned?

Thanks again for the details.  We'll definitely want to get more of this written down in the deploy notes after this PR is live.

**Comment by ramonaspence** [comment]
Yes. I've tested the start_date/end_date, the tags, and the response content_type in Postman. It looks like all is good 👍

**Comment by allella** [comment]
Alright. This is live and seems to be working.

Though, my Postman crashed locally and I don't want to restart my computer at the moment, so perhaps you can check the JSON+LD in Postman.

**Pull request merged**
