### PR TITLE
Development

### PR DESCRIPTION
**Pull request by ramonaspence**
This PR deletes files that are no longer referenced. 

I meant to have these deleted in my last PR. This PR won't change any functionality. 

Neither file is being referenced and none of the contents are being imported anywhere in the app. `Functions.py` was split into `update_functions.py` and `app_functions.py` while `search_engine_friendly.py` was my "whiteboard" for the function that reformats json to json+ld.

Sorry about that, I definitely thought I had deleted them, but evidently I had pushed before I did 😬 
I'm 100% embarrassed making this PR lol. 

EDIT: I know this shows 17 commits, but the second to last commit ([d0d3dae](https://github.com/codeforgreenville/upstate_tech_cal_service/pull/47/commits/d0d3daea5ce9ad70f7a94469049efa628799c504)) brought my development branch up to date with Code for Greenville's master branch. I triple checked that the only changes were deleting those two unused files.

Again, sorry. This is messy. I'm not sure if there's a better way to do this, but if there is, I would love to learn about it and apply that here. Now I'm 200% embarrassed 😅

### CODE REVIEW

**Comment by allella** [comment]
@ramonaspence it looks like this PR is based on a long running "development" branch.

I'm not GitHub wizard, but the result appears to be that this PR is trying to merge in all of your commits from the last PR we already merged in.

That would "probably" merge in, but could create a messy log and possibly future issues with unnecessary merge conflicts.

The way I've seen many other projects do it is that you keep your forked copy up to date with the "remote" origin, which is the main CFG repo.

The Chapter project I've helped with for years has pretty good docs, and we can also mostly copy something like that over to a CONTRIBUTING.md in this project and remove stuff that's not relevant.

It might be helpful to read that full file to see how these larger projects do things, which seems to be the best practice.

In particular, the [Using a Traditional Dev Environment]( https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md#using-a-traditional-dev-environment) section and "Step 4" go into how to create a new branch for each feature / PR.

In short, you'll want to make a note of the changes from your [most recent commit](https://github.com/codeforgreenville/upstate_tech_cal_service/pull/47/commits/a40eb955c75a10b365b3da1655c83870c3da7c1d). (There are ways to use git diff and git stash to do this, but it looks easy to just manually redo these changes on a fresh branch.

Then, delete the _development_ branch on your fork.  It's "old" in the sense that you already used it for a previous PR.

Branches should mostly be a one and done when you're submitting PRs.  That is, create a branch before you start working on a PR, commit to it, push it to your fork's origin and then when you go to GitHub it will have the UI to open a PR based on that branch.  Then, when your branch is merged in via a PR you delete that branch and create a new branch for the new PR you intend to do.   You can have multiple branches open at the same time if you're working on different things, but generally once they are merged it it's good / safe to delete that branch.

The "master" (or main, as is becoming the norm) is the only branch that typically stays around after a PR.

Again, this all will make more sense if you checkout https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md#using-a-traditional-dev-environment

**Comment by allella** [comment]
One common point of confusion with this GitHub / PR strategy is that it's not the only way.

It is possible in GitHub, and if you're using git outside of GitHub, to just create local branches and push them directly into the original project's repository.  That requires write permissions to the repo.

For example, I have write permissions and could push code directly into the https://github.com/codeforgreenville/upstate_tech_cal_service but that's frowned upon, even if you're the maintainer.  Rather, everyone is expected to create a fork and then create branches in their fork and then create PRs off those ephemeral branches.

**Comment by allella** [comment]
I've actually used a develop branch on the HackGreenville to maintain a staging branch / copy of the code, so that may also add to the confusion.

In the case of CFG, PRs are created against the "develop" branch because we merge PRs to it and then I pull that branch up to stage.hackgreenville.com and test a develop copy before merging the develop branch into the master branch.

I normally don't create a PR on HG for merging from develop to master, but I probably should.  So, understand that you may see release branches like that on the parent repo from which you've forked a project and they are usually for testing and deployment. Or, in some cases there may be versioned branches, like v1, v2 if you had a production API with multiple version of code.

There are also other, newer deployment strategies than that develop to master process I've been using for HG.  GitHub Actions and other tools can automate pushing code places for testing, but I haven't messed with that yet, so still doing the old-school way I know works okay until I learn the new way.

**Comment by allella** [comment]
So, I'm going to close this PR and please create a new branch in your fork. You can call it anything, but let's just say it's called _delete-unused-files_, apply the new changes from that last commit to that new branch, commit those changes to your _delete-unused-files_ branch, push that branch to your origin (_git push origin_), and then go to your fork on GitHub and it should have a dialog at the top of the page to create a new PR based on _delete-unused-files_ and you'd target the master branch of https://github.com/codeforgreenville/upstate_tech_cal_service on the other end of the PR.

**Comment by ramonaspence** [comment]
Thank you so much for being patient and kind enough to explain this. I wasn't thinking about the development branch being a one and done, but the way you explained the development branch being directly related to each PR makes it click more. 

I'm going to review this and the resources you linked again tomorrow morning. 

Then I will make the new branch, make the changes in this last commit to the new branch, push it to my origin and then create a PR on my fork targeting the master branch here, as you explained.

Thanks again for being patient with me!

**Pull request closed without merging**
