### PR TITLE
fix: deleted unused files

### PR DESCRIPTION
**Pull request by ramonaspence**
I've deleted the files, `functions.py` and `search_engine_friendly.py`, as they were no longer being used by or referenced in the app.

### CODE REVIEW

**Comment by allella** [comment]
Nailed it. Thanks.

**Comment by allella** [comment]
ramonaspence:fix/delete-unused-files can / should now be deleted.

You can delete it through the GitHub UI. I think there's usually a button at the bottom of the PR too that can be clicked to delete it.

Also, I typically run these commands on my local Git repos to keep things cleaned up when branches have been deleted.

`git remote prune origin && git gc --prune`

**Comment by allella** [comment]
And/or you can delete branches from your command line.
This is a special syntax that will DELETE a remote branch by pushing "nothing" to the origin / fork.

git push origin :fix/delete-unused-files

To delete a local branch.

git branch -d fix/delete-unused-files

**Comment by ramonaspence** [comment]
Awesome! Thanks again

This was a really good step for me in learning to use git.

**Pull request merged**
